spec/cronline_spec.rb, spec/job_every_spec.rb
Working correctly on EveryJob, but not on CronJob.
We observed this bug over the weekend, where jobs scheduled with a cron line in a DST-affected time zone were not scheduled for an hour during the transition. I'm not sure exactly how to fix yet; there seem to be bugs in `Rufus::Scheduler::CronLine#next_time` and `Rufus::Scheduler::CronLine#previous_time`. As far as I can tell these methods are incrementing/decrementing the time in UTC; thus ignoring DST transitions. Apart from that there's a whole section of logic in `next_time` that's missing in `previous_time`, causing fairly different results as seen below.
My instinct would be to change this code to use `ActiveSupport::TimeWithZone` rather than reinventing the wheel, but I'm not sure how people feel about adding an extra dependency. …
=> [DNM] Add failing specs for DST transitions

lib/rufus/scheduler/cronline.rb
I'm having an infinite loop computing the frequency of `1 2 3 4 5`, this change seems to fix this.
However I'm not sure why it should get into an infinite loop since the rest of the logic looks OK.
=> Infinite loop when computing frequency

lib/rufus/scheduler/zotime.rb
When tzinfo is not explicitly required, I'm getting *dozens* of [failures][] running specs or consuming this library (e.g., via resque-scheduler) on my local dev environment, despite the [CI build][] looking ok:
OS: Mac OSX 10.8.5 (`x86_64-darwin12.0`)
Ruby: 1.9.3-p551, 2.1.5, 2.1.6
This behaviour is new to 3.1.0 and was not present in 3.0.9.
The root cause for all of these failures appears to be `Rufus::Scheduler::ZoTime::is_timezone?` returning `true` for inputs like `"*"` or `"1,2,3,4,5"`, which are valid parts of a cronline and do not represent a timezone, which then causes the cronline to get [mangled][].
By adding an explicit require statement, we can ensure that `TZInfo` is used if available, which fixes my local problems, but it's unclear to me whether [the …
=> zotime: attempt to require tzinfo

lib/rufus/scheduler/jobs.rb, spec/schedule_cron_spec.rb
Fix for Issue #151. I am not sure if this is the right solution as if the job is created with a `first_at == Time.now`, the first_at would be ignored.
=> Fix Scheduler#timeline method stuck in infinite loop with a cron job using a 'first_in:' parameter

lib/rufus/scheduler/jobs.rb
When I make several jobs in a millisecond(same option), job ids are identical.. Later I couldn't retrieve one of the job instance by job method. 
I'm not sure, adding random number is a good solution.. But need to do something on this issue
=> Job id uniqueness

README.md
hi, i'm a nonbinary engineer, and having gendered language at all, *especially* "Sir," in a readme like this is incredibly off-putting and reinforces the idea that most programmers are men. gendered language isn't necessary, even if you're just trying to be playful to the reader. this is just a suggestion. thank you!
=> removed male-gendered language

lib/rufus/scheduler.rb, spec/job_spec.rb
While writing some tests for our internal scheduler based on rufus, I realized that `job.unscheduled_at` is not acknowledged in the `scheduled?` method. 
This pull request adds an additional check to the `scheduler.scheduled?` method to ensure the job is still scheduled when returning `true`.
=> Acknowledge unscheduled_at in scheduled? method

spec/cronline_spec.rb
https://github.com/jmettraux/rufus-scheduler/pull/140 added failing dst specs for summer time. We ran into this issue again this past weekend. I added failing specs for fall time.
Output of the failing tests:
```
Failures:
1) Rufus::Scheduler::CronLine fall time correctly increments through a DST transition
Failure/Error: expect(
expected: 2015-11-01 09:00:00.000000000 +0000
got: 2015-11-01 02:00:00.000000000 -0800
(compared using ==)
Diff:
@@ -1,2 +1,2 @@
-2015-11-01 09:00:00 UTC
+2015-11-01 02:00:00 -0800
2) Rufus::Scheduler::CronLine fall time correctly increments every minute through a DST transition
Failure/Error: expect(points).to eq(
expected: ["01:58:00l 08:58:00u", "01:59:00l 08:59:00u", "01:00:00l 09:00:00u", "01:01:00l 09:01:00u"]
got: ["01:58:00l 09:58:00u", "01:59:00l …
```
=> Add specs for DST transitions in the Fall

lib/rufus/scheduler/cronline.rb, spec/cronline_spec.rb
Added a spec to show case the issue, not sure if this is the best fix for it.
In some cases the current time sec was lower than all values in the secs array, this was causing pop to empty the array and eventually throw a nil comparison error.
=> fixes comparison of Fixnum with nil error

lib/rufus/scheduler/jobs.rb
Prior to v3, you could specify the option {first_in: 0} to have the scheduler fire the job immediately. This does not work anymore since only the symbols :now or :immediately are accounted for when setting @first_at to be slightly after Time.now (Time.now + 0.003).
Currently, @first_at will be set to Time.now if the options specify 0 and the scheduler won't fire the job until Time.now + frequency.
The [Dashing dashboard framework](http://shopify.github.io/dashing/) is forced to stay on v2.0.24 due to a large amount of [3rd party widgets](https://github.com/Shopify/dashing/wiki/Additional-Widgets) using {first_in: 0} to specify immediate execution of the scheduled job
=> Account for using {first: 0} for immediate execution of RepeatJobs

lib/rufus/scheduler/jobs.rb
Hi,
First I'd like to thank you for this awesome work on rufus-scheduler :)
I use rufus-scheduler (with resque-scheduler) in production to run jobs every 60s and I noticed that the schedule time shifted by ~1s every 15 minutes.
This was problematic to me because I rely heavily on time to do my computations, so I read the code and found the set_next_time method of Rufus::Scheduler::EveryJob was relying on the trigger time to define the next run of the job. I implemented a change to rely on the old @next_time value if it is defined to avoid time shift due to compute time or tick interval, it seems more logical and actually works perfectly for me.
What do you think ?
Please let me know if anything is unclear
Best regards,
=> fix potential time shift in EveryJob

lib/rufus/scheduler.rb
I was having issues with rufus + ActiveSupport(3.2.22) 
When checking for  @started_at == nil my system tried to use ActiveSupport's "compare_with_coercion" which ended up failing trying to run .to_datetime on null.
Not sure if I'm fixing this in the right place but I thought I'd give it a try.
=> Use .nil? instead of == nil

lib/rufus/scheduler/cronline.rb, spec/cronline_spec.rb
By breaking out of the loop as early as possible `brute_frequency` has to do less iterations, which significantly speeds up cronlines with second or minute intervals.
The cronline_spec now runs about 35 times faster.
=> Speedup brute frequency

lib/rufus/scheduler/cronline.rb, spec/cronline_spec.rb
The first commit ensures `previous_time` and `next_time` are not stuck in an infinite loop, which happened before when combining weekdays and monthdays in a cronline.
The second commit fixes that use case by modifying `date_match?` to only require one of the expressions to match if both are provided.
=> Support combination of weekdays and monthdays in cronline

lib/rufus/scheduler/cronline.rb, lib/rufus/scheduler/jobs.rb
in pre-2.4, Fixnum inherits from Integer; in 2.4+
it IS Integer. so it's safe to change these is_a? calls to
just check Integer
=> Fixnum is deprecated in ruby 2.4

lib/rufus/scheduler.rb
By using the `Scheduler` `lock` function instead of calling `@scheduler_lock.lock` directly. This means that overriding the lock function (as in the Zookeeper example in the docs) will actually do something.
=> Fix advanced locking interface

lib/rufus/scheduler/jobs.rb, spec/job_cron_spec.rb
Sometimes it's necessary to construct/modify a cronline object dynamically,
and this enables that object to be used as the schedule in addition
to the string parameter syntax.
=> Allow a CronLine object as parameter to schedule

lib/rufus/scheduler.rb, spec/schedule_cron_spec.rb
When working with large schedules of jobs (~100) that run infrequently (weekly or less) our Sidekiq server can take 8 to 10 minutes to start due to the check to ensure jobs don't run more frequently than the scheduler.
For Cron jobs, Fugit supports up to 1 second cron resolution, the entire check is skipped if the scheduler frequency is below that. Then based on a simple heuristic if the minimum delta between the 2nd, 3rd, and 4th runtimes is greater than a week the brute_frequency method is used. Otherwise the old enumeration logic over next_time_from is used.
I added simple specs to ensure adding both frequent and infrequent cron additions take less than a second (on master the infrequent spec takes 12 seconds).
This reduces the schedule parsing time for us to just under 20s.
=> Performance improvements for checking schedule intervals

README.md
Also use the ruby feature allowing you to skip the rest of a module with an early top level return (https://bugs.ruby-lang.org/issues/4840).
=> Update README for test env

lib/rufus/scheduler/util.rb
`parse_cron` method was expecting an "required" option hash as parameter but it was not used at all. This commit changes the parameter to an "optional" one and actually uses it to determine if the method should return nil or raise an error.(as other parse methods). `Fugit.do_parse_cron` is just like `parse_cron` but it raises an "ArgumentError" if the string cannot be parsed.
=> make us of opts in parse_cron and raise error

rufus-scheduler.gemspec
Rubyforge is long gone. As of rubygems 3.1, having this in the spec will cause a warning.
=> Remove rubyforge_project from specification

rufus-scheduler.gemspec
This reduces unnecessary redirection from http://... to https://... when someone visits this gem's homepage via https://rubygems.org/gems/rufus-scheduler or some tools or APIs that use the gem's metadata.
=> GitHub is HTTPS by default

lib/rufus/scheduler.rb
When using the rufus scheduler in a project with sorbet type checking, we get the following warning:
```bash
~/.gem/ruby/3.0.3/gems/rufus-scheduler-3.8.0/lib/rufus/scheduler.rb:587: warning: assigned but unused variable - e
```
use `_` instead of `e` to make it clear that it's an unused variable.
=> Fix warning: assigned but unused variable - e

.github/workflows/test.yaml
This PR uses the `bundler-cache` feature of the Ruby-maintained Action `ruby/setup-ruby`.
[See `ruby/setup-ruby` parameters declaration](https://github.com/ruby/setup-ruby/blob/master/action.yml) for more information.
=> CI: Avoid extra "bundle install"

lib/rufus/scheduler/jobs_repeat.rb, spec/job_repeat_spec.rb
First off - thanks for creating and maintaining this great library, my team has been using it for many years. However, one thing that has consistently plagued us throughout the years is the `ArgumentError` thrown if `first_at` is in the past. We use `rufus-scheduler` via `resque-scheduler`, and unfortunately we have seen wildly inconsistent performance when saving new schedules (sometimes up to 2 minutes between when we save and when rufus processes the schedule). Because of this, even if we pass in a `first_at` in the future, when rufus processes the job it is no longer in the future and throws an error and crashes the scheduler. As a workaround, we have had to add in an an artificial buffer that if our desired `first_at` is less than 2 minutes from now, set it to nil instead so rufus …
=> Optionally allow first_at to be set in the past

rufus-scheduler.gemspec
Pupular gems with 180M+ downloads implicitly requires that all privileged operations by any of the owners require OTP.
At the moment of this commit, `rufus-scheduler` has 109M+ downloads, so this commit makes the gem more secure by requiring that all privileged operations by any of the owners require OTP.
Also, by explicitly setting `rubygems_mfa_required` metadata, the gem will show "NEW VERSIONS REQUIRE MFA" and "VERSION PUBLISHED WITH MFA" in the sidebar at https://github.com/jmettraux/rufus-scheduler
Ref:
- https://blog.rubygems.org/2022/08/15/requiring-mfa-on-popular-gems.html
- https://guides.rubygems.org/mfa-requirement-opt-in/
=> Opt-in for MFA requirement
